language: node_js

dist: trusty
sudo: false

node_js:
  - '10'
  # no need to target older version as it is just to build

install:
  - yarn

script:
  - yarn run lint
  - yarn global add codecov
  - yarn run test:unit
  - yarn run build

after_success:
  - mv coverage/coverage-final.json coverage/coverage.json
  - codecov
